### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by gurmeherchawla** [zhuhaow/libnekit#19]
Hi. I've spend days trying to build.

On building the conanfile.py, I am getting the following error:
ERROR: libmaxminddb/1.3.2@zhuhaow/stable: Error in build() method, line 26
	self.run("autoreconf -fiv", run_environment=True)
	ConanException: Error 1 while executing DYLD_LIBRARY_PATH="" DYLD_FRAMEWORK_PATH="" autoreconf -fiv

On trying to build using CMake:
Make Error at CMakeLists.txt:110 (include):
  include could not find load file:

    /Users/Gurmeher/Downloads/libnekit-master/conanbuildinfo.cmake

CMake Error at CMakeLists.txt:111 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".

-- Configuring incomplete, errors occurred!

Please help

**Comment by zhuhaow** [comment]
Have you checked how the CI build everything? Honestly, I don’t recall how to build this project

**Comment by gurmeherchawla** [comment]
I've built all the packages using pipenv but having trouble with Conan package

**Comment by zhuhaow** [comment]
Try if sonar_build.sh would help, I see it uses cmake to build the project. 

I'll take a look later if that still doesn't work

**Comment by gurmeherchawla** [comment]
There's no sonar_build.sh or build_deps.py files

**Comment by zhuhaow** [comment]
The script is in `.travis/`

Have you tried just to use this project as a standard conan project?

**Comment by gurmeherchawla** [comment]
I'm a core iOS/macOS developer and am not familiar with the tools needed for building this project

**Comment by zhuhaow** [comment]
I updated document and Conan configuration in the `conan` branch, https://github.com/zhuhaow/libnekit/tree/conan

Since the CI is already down, I can't verify if everything works, so I'm not going to merge it to `master`.

However, I have to be honest before you invest more time in this project. If you find understanding how to use Conan is too difficult, think libnekit and its dependencies as something ten (or maybe more) times complicated and less documented. The document of libnekit is very sparse. Using a C++ library was, is, and probably will still be a nightmare in the foreseeable future. Using libnekit with iOS is not going to be easy since libnekit is highly templated and it probably won't play very well with objective-c++ (I've never tried), and building boost for ios is ridiculously difficult (that's part of the reason I switch to Conan). 

To make everything worse, I've already given up on working on C++ projects since I can't see how to maintain a library that works on multiple platforms and can be widely integrated with other languages as C does. If C++ can only work with C++ projects, it's probably better to use some language that at least less ugly and have a better ecosystem. So you see, if you see bugs or you have any feature requests, I can't help too much.

Anyway, I can still answer questions. Just proceed with caution.

**Comment by gurmeherchawla** [comment]
Thanks a lot for the swift responses and the heads up. 
I am actually looking for a tunnelling VPN. I have used the Tun2socks framework developed by you but have not been having a successful connection for vmess protocol. Is there any scope for the same using Tun2socks or libnekit?

**Comment by zhuhaow** [comment]
If you want VPN (at level 4), then use any existing vpn implementation (wireguard/openvpn/...)

If you just want to have a HTTP proxy, just write a proxy.

I'm not aware of any working tun2socks and technically speaking, there is no way to implement a correct tun2socks given there is no iptables equivalent on ios.
